app-id: cn.feishu.feishu
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
command: feishu
finish-args:
  - --share=network
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  # For camera
  - --device=all
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.freedesktop.secrets
  - --talk-name=org.gnome.keyring
  - --talk-name=org.gnome.ScreenSaver
  - --talk-name=org.kde.StatusNotifierWatcher
  - --talk-name=org.kde.kwin.Screenshot
  - --talk-name=org.kde.KWin.ScreenShot2
  - --own-name=org.kde.*
  - --system-talk-name=org.freedesktop.login1
  - --system-talk-name=org.freedesktop.UPower
  # Share files
  - --filesystem=xdg-documents
  - --filesystem=xdg-download
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:
  - name: feishu
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - install -Dm755 feishu -t ${FLATPAK_DEST}/bin
      - install -Dm755 apply_extra -t ${FLATPAK_DEST}/bin
      - install -Dm644 ${FLATPAK_ID}.svg -t ${FLATPAK_DEST}/share/icons/hicolor/scalable/apps
      - install -Dm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
    sources:
      - type: script
        commands:
          - export TMPDIR="${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}"
          - source /app/extra/feishu/bytedance-feishu.sh
          - exec zypak-wrapper /app/extra/feishu/feishu "$@"
        dest-filename: feishu
      - type: script
        commands:
          - bsdtar --to-stdout -xf feishu-linux.deb data.tar.xz | bsdtar -xf -
          - mv opt/bytedance/feishu .
          - sed '/^exec -a/d' feishu/bytedance-feishu > feishu/bytedance-feishu.sh
          - rm -rf opt usr *.deb
        dest-filename: apply_extra
      - type: extra-data
        filename: feishu-linux.deb
        url: https://sf3-cn.feishucdn.com/obj/ee-appcenter/18b9e5d0/Feishu-linux_x64-7.32.11.deb
        sha256: 814f9f362504da4084df8d3bbdd8d0a84ee82e047dbd7ca768136e577119aea7
        size: 382623684
        only-arches: [x86_64]
        x-checker-data:
          type: json
          url: https://www.feishu.cn/api/downloads
          version-query: .versions.Linux_deb_x64.version_number | capture("@V(?<v>.*)")
            | .v
          url-query: .versions.Linux_deb_x64.download_link
      - type: extra-data
        filename: feishu-linux.deb
        url: https://sf3-cn.feishucdn.com/obj/ee-appcenter/8946d4de/Feishu-linux_arm64-7.32.11.deb
        sha256: 818210cac6c823d51dd5aede5ea411b4eb01036ac8dbdfb19f19ed02e98551d9
        size: 349248568
        only-arches: [aarch64]
        x-checker-data:
          type: json
          url: https://www.feishu.cn/api/downloads
          version-query: .versions.Linux_deb_arm.version_number | capture("@V(?<v>.*)")
            | .v
          url-query: .versions.Linux_deb_arm.download_link
      - type: file
        path: cn.feishu.feishu.desktop
      - type: file
        path: cn.feishu.feishu.metainfo.xml
      - type: file
        path: cn.feishu.feishu.svg
