app-id: io.github.predidit.kazumi
runtime: org.gnome.Platform
runtime-version: '46'
sdk: org.gnome.Sdk
command: kazumi
finish-args:
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --share=network
  - --device=dri
  - --talk-name=org.kde.StatusNotifierWatcher

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    directory: lib/ffmpeg
    version: '24.08'
    add-ld-path: .

modules:
  - shared-modules/libayatana-appindicator/libayatana-appindicator-gtk3.json

  - name: kazumi
    buildsystem: simple
    build-commands:
      - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
      - mv opt/Kazumi /app/
      - cp -a usr/share /app/
      - chmod +x /app/Kazumi/kazumi
      - install -Dm755 kazumi.sh /app/bin/kazumi
      - install -Dm644 io.github.predidit.kazumi.metainfo.xml -t /app/share/metainfo
      - mkdir -p /app/lib/ffmpeg
    sources:
      - type: file
        only-arches: [x86_64]
        url: https://github.com/Predidit/Kazumi/releases/download/1.3.6/Kazumi_linux_1.3.6_amd64.deb
        sha256: af5ef12f0621cde0c73f885e962c1457589d5af53fbe6da0f36d3f3e44a9a08b
        x-checker-data:
          type: json
          url: https://api.github.com/repos/Predidit/Kazumi/releases/latest
          version-query: .tag_name
          url-query: >-
            .assets[] | select(.name=="Kazumi_linux_" + $version + "_amd64.deb") |
            .browser_download_url
      - type: file
        path: io.github.predidit.kazumi.metainfo.xml
      - type: script
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - /app/Kazumi/kazumi
        dest-filename: kazumi.sh
