app-id: io.github.msojocs.bilibili
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
separate-locales: false
command: bilibili

finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --device=dri
  - --share=network
  - --filesystem=xdg-videos
  - --filesystem=xdg-download
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
  - --talk-name=org.freedesktop.ScreenSaver
  # required to fix cursor scaling on wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    directory: lib/ffmpeg
    version: '24.08'
    add-ld-path: .

modules:
  - name: bilibili
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - install -Dm644 io.github.msojocs.bilibili.desktop -t /app/share/applications
      - install -Dm644 io.github.msojocs.bilibili.svg -t /app/share/icons/hicolor/scalable/apps/
      - install -Dm644 io.github.msojocs.bilibili.metainfo.xml -t /app/share/metainfo
      - install -Dm755 bilibili.sh /app/bin/bilibili
      - install -Dm755 apply_extra -t /app/bin
      - ln -svf /usr/bin/ffmpeg /app/bin/
      - mkdir -p /app/lib/ffmpeg
    sources:
      - type: extra-data
        only-arches: [aarch64]
        url: https://github.com/msojocs/bilibili-linux/releases/download/v1.14.2-1/io.github.msojocs.bilibili_1.14.2-1_arm64.deb
        sha256: 5e37ddff562260163e0a860b238a99bb03876df7d03877ba12bd4511e4233f72
        filename: bilibili.deb
        size: 83931152
        x-checker-data:
          type: json
          url: https://api.github.com/repos/msojocs/bilibili-linux/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name=="io.github.msojocs.bilibili_" + $version + "_arm64.deb")
            |
            .browser_download_url
      - type: extra-data
        only-arches: [x86_64]
        url: https://github.com/msojocs/bilibili-linux/releases/download/v1.14.2-1/io.github.msojocs.bilibili_1.14.2-1_amd64.deb
        sha256: 9f49fbcc70f287d2420693c2e45ebd6eba03af958c01dca284903370f5c1cc31
        filename: bilibili.deb
        size: 87893708
        x-checker-data:
          type: json
          url: https://api.github.com/repos/msojocs/bilibili-linux/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name=="io.github.msojocs.bilibili_" + $version + "_amd64.deb")
            |
            .browser_download_url
      - type: file
        path: io.github.msojocs.bilibili.metainfo.xml
      - type: file
        path: io.github.msojocs.bilibili.desktop
      - type: file
        path: io.github.msojocs.bilibili.svg
      - type: script
        dest-filename: bilibili.sh
        commands:
          - export TMPDIR=$XDG_RUNTIME_DIR/app/$FLATPAK_ID
          - export ELECTRON_IS_DEV=0
          - export ELECTRON_FORCE_IS_PACKAGED=true
          - export ELECTRON_DISABLE_SECURITY_WARNINGS=true
          - export NODE_ENV=production
          - WAYLAND_SOCKET=${WAYLAND_DISPLAY:-"wayland-0"}
          - |
            if [[ -e "$XDG_RUNTIME_DIR/${WAYLAND_SOCKET}" || -e "${WAYLAND_DISPLAY}" ]]
            then
                FLAGS="--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime"
            fi
          - exec zypak-wrapper "/app/extra/bilibili/electron/electron" "/app/extra/bilibili/app/app.asar" $FLAGS "$@"
      - type: script
        commands:
          - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
          - mv opt/apps/io.github.msojocs.bilibili/files/bin ./bilibili
          - rm -r *.deb usr opt
        dest-filename: apply_extra