id: io.github.PBH_BTN.PeerBanHelper
runtime: org.freedesktop.Platform
runtime-version: "24.08"
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk21
command: peerbanhelper
finish-args:
  - --share=ipc
  - --socket=x11
  - --share=network
  - --env=PATH=/app/jre/bin:/app/bin:/usr/bin
  - --persist=data
cleanup:
  - "*.a"
  - "*.la"
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - name: openjdk
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/openjdk21/install.sh

  - name: PeerBanHelper
    buildsystem: simple
    build-commands:
      - install -Dm755 peerbanhelper -t ${FLATPAK_DEST}/bin/
      - install -Dm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications/
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo/
      - install -Dm644 ${FLATPAK_ID}.png -t ${FLATPAK_DEST}/share/icons/hicolor/256x256/apps/
      - install -Dm755 apply_extra -t ${FLATPAK_DEST}/bin/
    sources:
      - type: extra-data
        url: https://github.com/PBH-BTN/PeerBanHelper/releases/download/v7.0.1/peerbanhelper_7.0.1_all.deb
        filename: peerbanhelper.deb
        sha256: f70519a96d69dc67a0ad448b045d502e84f8398df01309fa03df88266530553a
        size: 49961046
        x-checker-data:
          type: json
          url: https://api.github.com/repos/PBH-BTN/PeerBanHelper/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name=="peerbanhelper_" + $version + "_all.deb") | .browser_download_url

      - type: file
        path: io.github.PBH_BTN.PeerBanHelper.metainfo.xml

      - type: file
        path: io.github.PBH_BTN.PeerBanHelper.png

      - type: file
        path: io.github.PBH_BTN.PeerBanHelper.desktop

      - type: script
        commands:
          - java -Dpbh.release=debian -Dpbh.datadir=${XDG_CONFIG_HOME}/peerbanhelper -Xmx512M -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ShrinkHeapInSteps -jar /app/extra/peerbanhelper/PeerBanHelper.jar
        dest-filename: peerbanhelper

      - type: script
        commands:
          - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
          - mv usr/lib/peerbanhelper .
          - rm -rf etc usr
        dest-filename: apply_extra