app-id: io.github.wgh136.pixes
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm19
command: pixes
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
  - --own-name=com.github.wgh136.pixes
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - name: pixes
    buildsystem: simple
    build-options:
      append-path: /usr/lib/sdk/llvm19/bin
      prepend-ld-library-path: /usr/lib/sdk/llvm19/lib
      arch:
        x86_64:
          env:
            FLUTTER_ARCH: x64
        aarch64:
          env:
            FLUTTER_ARCH: arm64
      build-args:
        - --share=network
    build-commands:
      - git clone --branch 3.29.0 https://github.com/flutter/flutter.git
      - flutter/bin/flutter build linux --release
      - cp -rv build/linux/${FLUTTER_ARCH}/release/bundle ${FLATPAK_DEST}/pixes
      - install -Dm755 pixes.sh ${FLATPAK_DEST}/bin/pixes
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo/
      - install -Dm644 debian/gui/pixes.desktop ${FLATPAK_DEST}/share/applications/${FLATPAK_ID}.desktop
      - install -Dm644 debian/gui/pixes.png ${FLATPAK_DEST}/share/icons/hicolor/128x128/apps/${FLATPAK_ID}.png
      - desktop-file-edit --set-key="Categories" --set-value="Graphics;Network;" --set-key="Exec" --set-value="pixes" --set-key="Icon" --set-value="io.github.wgh136.pixes" ${FLATPAK_DEST}/share/applications/${FLATPAK_ID}.desktop
    sources:
      - type: git
        url: https://github.com/wgh136/pixes.git
        tag: v1.1.1
        commit: cbc69b4707b068a5cc6ec3df87741a9658288b33
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+)$
      - type: file
        path: io.github.wgh136.pixes.metainfo.xml
      - type: script
        commands:
          - /app/pixes/pixes "$@"
        dest-filename: pixes.sh
