app-id: top.jtmonster.jhentai
runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk
command: jhentai
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - name: jhentai
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
      - cp -a usr/share ${FLATPAK_DEST}/
      - mv opt/jhentai ${FLATPAK_DEST}/
      - install -Dm755 jhentai.sh ${FLATPAK_DEST}/bin/jhentai
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
    sources:
      - type: file
        only-arches: [x86_64]
        url: https://github.com/jiangtian616/JHenTai/releases/download/v8.0.6%2B277/JHenTai-8.0.6%2B277-Linux-x64.deb
        sha256: 86aa149bcf2ff4c8760e7e904810f7a8e5be9da3c33cbe02201b67264087bc2b
        x-checker-data:
          type: json
          url: https://api.github.com/repos/jiangtian616/JHenTai/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name | test("^JHenTai-.*-Linux-x64\\.deb$"))
            |
            .browser_download_url
      - type: file
        only-arches: [aarch64]
        url: https://github.com/jiangtian616/JHenTai/releases/download/v8.0.6%2B277/JHenTai-8.0.6%2B277-Linux-arm64.deb
        sha256: 8525016ef3b2831fd950c335537927176479695e09676e1f26e866c35e961204
        x-checker-data:
          type: json
          url: https://api.github.com/repos/jiangtian616/JHenTai/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: >-
            .assets[] | select(.name | test("^JHenTai-.*-Linux-arm64\\.deb$"))
            |
            .browser_download_url
      - type: file
        path: top.jtmonster.jhentai.metainfo.xml
      - type: script
        commands:
          - export TMPDIR="${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}"
          - exec /app/jhentai/jhentai "$@"
        dest-filename: jhentai.sh
