# This file is used to generate flutter sources
# https://github.com/TheAppgineer/flatpak-flutter
app-id: top.jtmonster.jhentai
runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm19
command: jhentai
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - name: jhentai
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      append-path: /usr/lib/sdk/llvm19/bin
      prepend-ld-library-path: /usr/lib/sdk/llvm19/lib
      env:
        PUB_CACHE: /run/build/jhentai/.pub-cache
    build-commands:
      - flutter/bin/flutter build linux --release --verbose --target lib/src/main.dart
    sources:
      - type: git
        url: https://github.com/jiangtian616/JHenTai.git
        tag: v8.0.6+277
        commit: 8bc13ab2b678907e2bafd0724bde4ac6c342f8a2
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+(?:\+\d+)?)$
      - type: file
        path: top.jtmonster.jhentai.metainfo.xml
      - type: git
        url: https://github.com/flutter/flutter.git
        tag: 3.24.5
        dest: flutter
      # Workaround: To keep engine.version and allow shallow clones: https://github.com/flutter/flutter/issues/163308
      - type: shell
        commands:
          - rm -f flutter/engine/src/.gn
