app-id: io.github.venera_app.venera
runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm19
command: venera
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
  - --talk-name=org.freedesktop.ScreenSaver
  - --system-talk-name=org.freedesktop.NetworkManager
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:

  - name: rustup
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      env:
        CARGO_HOME: /var/lib/rustup
        RUSTUP_HOME: /var/lib/rustup
    build-commands:
      - chmod +x rustup-init && ./rustup-init -y --profile minimal --no-modify-path
    sources:
      - type: file
        only-arches: [x86_64]
        url: https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
        sha256: 6aeece6993e902708983b209d04c0d1dbb14ebb405ddb87def578d41f920f56d
      - type: file
        only-arches: [aarch64]
        url: https://static.rust-lang.org/rustup/dist/aarch64-unknown-linux-gnu/rustup-init
        sha256: 1cffbf51e63e634c746f741de50649bbbcbd9dbe1de363c9ecef64e278dba2b2

  - name: venera
    buildsystem: simple
    build-options:
      build-args:
        - --share=network
      arch:
        x86_64:
          env:
            BUNDLE_PATH: build/linux/x64/release/bundle
        aarch64:
          env:
            BUNDLE_PATH: build/linux/arm64/release/bundle
      append-path: /var/lib/rustup/bin:/usr/lib/sdk/llvm19/bin:/run/build/venera/flutter/bin
      prepend-ld-library-path: /usr/lib/sdk/llvm19/lib
      env:
        RUSTUP_HOME: /var/lib/rustup
        CARGO_HOME: /run/build/venera/cargo
        PUB_CACHE: /run/build/venera/.pub-cache
    build-commands:
      - flutter build linux --release --verbose
      - mkdir -p ${FLATPAK_DEST}/bin
      - cp -r ${BUNDLE_PATH}/* ${FLATPAK_DEST}/bin
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dm644 debian/gui/venera.desktop ${FLATPAK_DEST}/share/applications/${FLATPAK_ID}.desktop
      - install -Dm644 debian/gui/venera.png ${FLATPAK_DEST}/share/icons/hicolor/64x64/apps/${FLATPAK_ID}.png
      - desktop-file-edit --set-key="Categories" --set-value="Graphics;Network;" --set-key="Exec"
        --set-value="venera" --set-key="Icon" --set-value="io.github.venera_app.venera"
        ${FLATPAK_DEST}/share/applications/${FLATPAK_ID}.desktop
    sources:
      - type: git
        url: https://github.com/venera-app/venera.git
        tag: v1.3.1
        commit: 587c5d804063a760c735de02ff4bc88dffc7b42e
        x-checker-data:
          type: git
          tag-pattern: ^v([\d.]+)$
      - type: file
        path: io.github.venera_app.venera.metainfo.xml
      - type: git
        url: https://github.com/flutter/flutter.git
        tag: 3.27.4
        commit: d8a9f9a52e5af486f80d932e838ee93861ffd863
        dest: flutter
