id: org.freedesktop.Sdk.Extension.flutter
branch: '24.08'
runtime: org.freedesktop.Sdk
build-extension: true
sdk: org.freedesktop.Sdk
runtime-version: '24.08'
separate-locales: false
modules:
  - name: flutter
    buildsystem: simple
    sources:
      - type: git
        url: https://github.com/flutter/flutter.git
        tag: 3.29.0
        commit: 35c388afb57ef061d06a39b537336c87e0e3d1b1
        x-checker-data:
          type: git
          tag-pattern: ^([\d.]+)$
    build-options:
      build-args:
        - --share=network
    build-commands:
      - bin/flutter doctor -v
      - install -d /usr/lib/sdk/flutter
      - cp -rpv * /usr/lib/sdk/flutter/

  - name: scripts
    sources:
      - type: script
        commands:
          - export PATH=$PATH:/usr/lib/sdk/flutter/bin
        dest-filename: enable.sh
    buildsystem: simple
    build-commands:
      - cp enable.sh /usr/lib/sdk/flutter/

  - name: metainfo
    buildsystem: simple
    build-commands:
      - install -Dm0644 org.freedesktop.Sdk.Extension.flutter.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
    sources:
      - type: file
        path: org.freedesktop.Sdk.Extension.flutter.metainfo.xml
