app-id: com.xiaoyaocz.dmzjx
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
rename-icon: ZAI-X
rename-desktop-file: ZAI-X.desktop
command: ZAI-X
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --device=dri
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc
modules:
  - name: ZAI-X
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
      - mv usr/share/ZAI-X /app/
      - mv usr/share /app/
      - desktop-file-edit --set-key="Categories" --set-value="Graphics;Network;" --remove-key="Version"
        /app/share/applications/ZAI-X.desktop
      - chmod +x /app/ZAI-X/ZAI-X
      - install -Dm755 ZAI-X.sh /app/bin/ZAI-X
      - install -Dm644 com.xiaoyaocz.dmzjx.metainfo.xml -t /app/share/metainfo
    sources:
      - type: file
        url: https://github.com/xiaoyaocz/flutter_dmzj/releases/download/zaix/v1.0.3-test/flutter_dmzj-1.0.3%2B10003-linux.deb
        only-arches: [x86_64]
        sha256: 053a890777dd4d756feb7821b0f853733d3a947abcae949b10bbaf92df458ed6
        x-checker-data:
          type: json
          url: https://api.github.com/repos/xiaoyaocz/flutter_dmzj/releases/latest
          version-query: .tag_name | sub("^zaix/v"; "") | sub("-test$"; "")
          url-query: .assets[] | select(.name | contains("linux") and contains("deb"))
            | .browser_download_url

      - type: file
        path: com.xiaoyaocz.dmzjx.metainfo.xml

      - type: script
        commands:
          - export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
          - /app/ZAI-X/ZAI-X "$@"
        dest-filename: ZAI-X.sh
