app-id: com.visualstudio.code
runtime: org.freedesktop.Sdk
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.golang
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
command: code
tags: [proprietary]
separate-locales: false
finish-args:
  - --require-version=0.10.3
  - --share=network
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --socket=ssh-auth
  - --device=all
  - --allow=devel
  - --filesystem=host
  - --env=NPM_CONFIG_GLOBALCONFIG=/app/etc/npmrc
  - --env=LD_LIBRARY_PATH=/app/lib
  # required to fix cursor scaling on wayland
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
  - --system-talk-name=org.freedesktop.login1
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.freedesktop.secrets
  - --talk-name=org.freedesktop.Flatpak
  - --talk-name=com.canonical.AppMenu.Registrar
  - --talk-name=com.canonical.AppMenu.Registrar.*
add-extensions:
  com.visualstudio.code.tool:
    directory: tools
    subdirectories: true
    versions: stable;24.08
    add-ld-path: lib
    no-autodownload: true
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/doc
  - /share/gtk-doc
modules:
  - shared-modules/libusb/libusb.json

  # Provide libsecret without gcrypt, forcing it to use the D-Bus backend
  # https://github.com/flathub/org.signal.Signal/pull/756/commits/2caf105b18f906e7707f67b3cf7384a21f461564
  - name: libsecret
    buildsystem: meson
    config-opts:
      - -Dmanpage=false
      - -Dcrypto=disabled
      - -Dvapi=false
      - -Dgtk_doc=false
      - -Dintrospection=false
      - -Dbash_completion=disabled
    cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /share/man
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/libsecret.git
        tag: 0.21.6
        commit: e59012225c2857d53738574423416b541f11a131
        x-checker-data:
          type: git
          tag-pattern: ^([\d.]+)$

  - name: vscode
    buildsystem: simple
    build-commands:
      - install -Dm755 code.sh ${FLATPAK_DEST}/bin/code
      - install -Dm644 vscode_64.png ${FLATPAK_DEST}/share/icons/hicolor/64x64/apps/${FLATPAK_ID}.png
      - install -Dm644 vscode_128.png ${FLATPAK_DEST}/share/icons/hicolor/128x128/apps/${FLATPAK_ID}.png
      - install -Dm644 vscode_256.png ${FLATPAK_DEST}/share/icons/hicolor/256x256/apps/${FLATPAK_ID}.png
      - install -Dm644 vscode_512.png ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps/${FLATPAK_ID}.png
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dm644 ${FLATPAK_ID}-url-handler.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dm644 ${FLATPAK_ID}-workspace.xml -t ${FLATPAK_DEST}/share/mime/packages
      - install -Dm644 npmrc -t ${FLATPAK_DEST}/etc
      - install -Dm644 flatpak-warning.txt -t ${FLATPAK_DEST}/share/vscode
      - install -Dm755 apply_extra -t ${FLATPAK_DEST}/bin
      - mkdir ${FLATPAK_DEST}/tools
    sources:
      - type: script
        dest-filename: apply_extra
        commands:
          - bsdtar --to-stdout -xf code.deb data.* | bsdtar --no-same-owner -xf -
          - mv usr/share/code vscode
          - rm -r code.deb usr
      - type: file
        path: code.sh
      - type: file
        path: flatpak-warning.txt
      - type: file
        path: npmrc
      - type: file
        path: com.visualstudio.code.metainfo.xml
      - type: file
        path: com.visualstudio.code.desktop
      - type: file
        path: com.visualstudio.code-url-handler.desktop
      - type: file
        path: com.visualstudio.code-workspace.xml
      - type: file
        path: icons/vscode_64.png
      - type: file
        path: icons/vscode_128.png
      - type: file
        path: icons/vscode_256.png
      - type: file
        path: icons/vscode_512.png
      - type: extra-data
        filename: code.deb
        only-arches: [x86_64]
        url: https://update.code.visualstudio.com/1.97.2/linux-deb-x64/stable
        sha256: 330542e60688faf96c577d8fdce4d03b4638a4d7245189cdf717804ffb09ed40
        size: 105232506
        x-checker-data:
          type: json
          url: https://api.github.com/repos/microsoft/vscode/releases/latest
          version-query: .tag_name
          timestamp-query: .published_at
          url-query: '"https://update.code.visualstudio.com/" + $version + "/linux-deb-x64/stable"'
          is-main-source: true

      - type: extra-data
        filename: code.deb
        only-arches: [aarch64]
        url: https://update.code.visualstudio.com/1.97.2/linux-deb-arm64/stable
        sha256: 5553ae85b0799bcefdcc350a3466debb4a96893f138f373cfb47b3c83641ca59
        size: 97645242
        x-checker-data:
          type: json
          url: https://api.github.com/repos/microsoft/vscode/releases/latest
          version-query: .tag_name
          timestamp-query: .published_at
          url-query: '"https://update.code.visualstudio.com/" + $version + "/linux-deb-arm64/stable"'

  - name: krb5
    buildsystem: simple
    build-commands:
      - autoreconf -i
      - ./configure --prefix=${FLATPAK_DEST}
      - make -j ${FLATPAK_BUILDER_N_JOBS}
      - make install
      - install -Dm644 ../krb5.conf -t ${FLATPAK_DEST}/etc
    subdir: src
    sources:
      - type: git
        url: https://github.com/krb5/krb5.git
        tag: krb5-1.21.3-final
        commit: 8f56f544dd179056e9b8d02552e6c5e392eb2966
        x-checker-data:
          type: git
          tag-pattern: ^krb5-([\d.]+)-final$
      - type: file
        path: krb5.conf

  - name: host-spawn
    buildsystem: simple
    build-options:
      append-path: /usr/lib/sdk/golang/bin
    build-commands:
      - CGO_ENABLED=0 go build -mod=vendor -o "${FLATPAK_DEST}/bin/host-spawn"
    sources:
      - type: archive
        url: https://github.com/1player/host-spawn/releases/download/v1.6.1/host-spawn-vendor.tar.zst
        sha256: 17e5d4846b0532467035523a742a11e60f31766b3f237a06e7b75daf7858ab3c
        x-checker-data:
          type: json
          url: https://api.github.com/repos/1player/host-spawn/releases/latest
          tag-query: .tag_name
          version-query: .tag_name
          timestamp-query: .published_at
          url-query: '[.assets[] | select(.name|test(".+tar.zst$"))][0] | .browser_download_url'
