app-id: com.qq.docs
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
base: org.electronjs.Electron2.BaseApp
base-version: '24.08'
separate-locales: false
command: tdappdesktop

finish-args:
  - --share=ipc
  - --socket=x11
  - --device=dri
  - --share=network
  - --filesystem=xdg-download
  - --talk-name=org.kde.StatusNotifierWatcher

cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/debug
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

modules:
  - name: docs
    buildsystem: simple
    build-options:
      no-debuginfo: true
    build-commands:
      - install -Dm755 apply_extra -t ${FLATPAK_DEST}/bin
      - install -Dm644 ${FLATPAK_ID}.svg -t ${FLATPAK_DEST}/share/icons/hicolor/scalable/apps
      - install -Dm644 ${FLATPAK_ID}.desktop -t ${FLATPAK_DEST}/share/applications
      - install -Dm644 ${FLATPAK_ID}.metainfo.xml -t ${FLATPAK_DEST}/share/metainfo
      - install -Dm755 tdappdesktop.sh ${FLATPAK_DEST}/bin/tdappdesktop
    sources:
      - type: extra-data
        only-arches: [aarch64]
        filename: docs.deb
        url: https://desktop.docs.qq.com/Installer/30001/3.9.0/TencentDocs-arm64.deb
        sha256: e9a3c6a9a5943b6cb6448b3016a37585aff4da6a68af7b33f33e4588ef4ea6a5
        size: 151397154
        x-checker-data:
          type: json
          url: https://docs.qq.com/api/package/update
          version-query: .result.update_info | fromjson | .version
          url-query: '"https://desktop.docs.qq.com/Installer/30001/\($version)/TencentDocs-arm64.deb"'
      - type: extra-data
        only-arches: [x86_64]
        filename: docs.deb
        url: https://desktop.docs.qq.com/Installer/30001/3.9.0/TencentDocs-x64.deb
        sha256: a4bfb9521dd125554912d4cd55220731eb1c6ef976b9fab0dcb9fdd23540bbbf
        x-checker-data:
          type: json
          url: https://docs.qq.com/api/package/update
          version-query: .result.update_info | fromjson | .version
          url-query: '"https://desktop.docs.qq.com/Installer/30001/\($version)/TencentDocs-x64.deb"'
        size: 156377250
      - type: file
        path: ${FLATPAK_ID}.metainfo.xml
      - type: file
        path: ${FLATPAK_ID}.svg
      - type: file
        path: ${FLATPAK_ID}.desktop
      - type: script
        dest-filename: tdappdesktop.sh
        commands:
          - export TMPDIR=${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}
          - WAYLAND_SOCKET=${WAYLAND_DISPLAY:-"wayland-0"}
          - |
            if [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_SOCKET}" || -e "${WAYLAND_DISPLAY}" ]]
            then
                FLAGS="--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime"
            fi
          - exec zypak-wrapper.sh /app/extra/docs/tdappdesktop $FLAGS "$@"
      - type: script
        commands:
          - bsdtar --to-stdout -xf *.deb data.* | bsdtar -xf -
          - mv opt/腾讯文档 ./docs
          - rm -rf *.deb usr opt
        dest-filename: apply_extra
