name: Update

on:
  push:
    paths: 
      - .github/workflows/update.yaml
  schedule: # for scheduling to work this file must be in the default branch
     - cron: "0 12 * * *" # 每天中午12点运行一次
       paths:  # 仅当清单文件变更时才触发
         - 'manifests/**/*.yml'
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        appid: # list all flatpak application id to check
          # - io.github.arvinlovegood.go-stock
          - com.cherry_ai.cherrystudio
          - io.github.venera_app.venera
          - io.github.wgh136.pixes
          - top.jtmonster.jhentai
          - com.xiaoyaocz.simplelive
          - cn.wps.office
          - com.qq.docs
          - com.qq.weixin
          - com.qq.qqmusic
          - io.github.c0re100.qBittorrent-Enhanced-Edition
          - io.github.msojocs.bilibili
          - io.github.PBH_BTN.PeerBanHelper
          - org.freedesktop.xorg.xeyes
          - com.cursor.cursor
          - com.larksuite.lark
          - com.qq.qq
          - org.freedesktop.Platform.Electron
    steps:
      - uses: actions/checkout@v4 
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork manifests/${{ matrix.appid }}/${{ matrix.appid }}.yml # e.g. com.organization.myapp.json
